services:
  postgres:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./app/dist/files:/app/dist/files
      - ./app/dist/files/profiles:/app/dist/files/profiles
      - ./app/dist/files/verifications:/app/dist/files/verifications
      - ./app/dist/files/trails:/app/dist/files/trails
      - ./app/dist/files/peaks:/app/dist/files/peaks
      - ./backend/data/exportMain.geojson:/app/data/exportMain.geojson:ro
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - REFRESH_SECRET_TOKEN=${REFRESH_SECRET_TOKEN}
      - ORS_API_KEY=${ORS_API_KEY}
      - API_KEY=${API_KEY}
      - FILES_DIR=/app/dist/files
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/workspace/frontend
      - /workspace/frontend/node_modules
    environment:
      - TZ=Europe/Warsaw
      - VITE_CLIENT_API_URL=${VITE_CLIENT_API_URL}
      - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
      - VITE_WEATHER_CITY=${VITE_WEATHER_CITY}
    command: npm run dev -- --host 0.0.0.0