services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty123!
      POSTGRES_DB: HikeUp
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./postgresql:/backup
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  backend:
    build: ./backend
    ports:
      - "6868:6868"
    volumes:
      - ./app/dist/files:/app/dist/files
      - ./app/dist/files/profiles:/app/dist/files/profiles
      - ./app/dist/files/verifications:/app/dist/files/verifications  
      - ./app/dist/files/trails:/app/dist/files/trails
      - ./backend/data/exportMain.geojson:/app/data/exportMain.geojson:ro
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=qwerty123!
      - DB_NAME=HikeUp
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
      - ./frontend/index.html:/frontend/index.html
    environment:
      - TZ=Europe/Warsaw
    networks:
      - frontend
    command: npm run dev
volumes:
  postgres_data:

networks:
  backend:
  frontend: