services:
  postgres:
    image: postgis/postgis:15-3.4
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql:/backup
    # ports - NIE wystawiamy bazy na zewnątrz, tylko backend ma dostęp
    networks:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "0.0.0.0:6868:6868"
    volumes:
      - ./app/dist/files:/app/dist/files
      - ./app/dist/files/profiles:/app/dist/files/profiles
      - ./app/dist/files/verifications:/app/dist/files/verifications
      - ./app/dist/files/trails:/app/dist/files/trails
      - ./app/dist/files/peaks:/app/dist/files/peaks
      - ./backend/data/exportMain.geojson:/app/data/exportMain.geojson:ro
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - REFRESH_SECRET_TOKEN=${REFRESH_SECRET_TOKEN}
      - ORS_API_KEY=${ORS_API_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    restart: unless-stopped

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Warsaw
      - VITE_CLIENT_API_URL=${VITE_CLIENT_API_URL}
      - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
      - VITE_WEATHER_CITY=${VITE_WEATHER_CITY}
    networks:
      - frontend
   

volumes:
  postgres_data:

networks:
  backend:
  frontend: